name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --all --tags

      # This fails if the tag or file already exists
      - name: Check if version has been updated
        id: check
        uses: thebongy/version-check@v1
        with:
          file: "Cargo.toml"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.check.outputs.releaseVersion }}
          release_name: Release ${{ steps.check.outputs.releaseVersion }}
          body: ${{ github.ref }}
          draft: false
          prerelease: false

      # Publish to cargo start
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: "Publish with cargo"
        uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CARGO_TOKEN }}

      # Publish to NPM start
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: "Publish with NPM"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          wasm-pack build
          npm publish ./pkg
